onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider Master
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/CLEAR
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/CLK
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/CLK_EN
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/CLK_RX_FULL_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/CLK_RX_HALF_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/CTRL_DEBUG
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/CTRL_OP
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/IS_SLAVE
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/MED_DATAREADY_IN
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/MED_DATAREADY_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/MED_DATA_IN
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/MED_DATA_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/MED_PACKET_NUM_IN
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/MED_PACKET_NUM_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/MED_READ_IN
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/MED_READ_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/RESET
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/RX_DLM
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/RX_DLM_WORD
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/SERDES_NUM
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/STAT_DEBUG
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/STAT_OP
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/SYSCLK
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/TX_DLM
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/TX_DLM_WORD
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/clk_200_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/clk_200_internal
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/clk_rx_full
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/clk_rx_half
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/clk_tx_full
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/clk_tx_half
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/debug_reg
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/debug_rx_control_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/debug_tx_control_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/got_link_ready_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/lsm_status
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/make_link_reset_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/request_retr_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/request_retr_position_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/rst_n
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/rst_qd
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/rx_allow
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/rx_cdr_lol
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/rx_data
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/rx_error
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/rx_fsm_state
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/rx_k
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/rx_los_low
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/rx_pcs_rst
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/rx_serdes_rst
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/send_link_reset_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/serdes_rst_qd
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/start_retr_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/start_retr_position_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/start_timer
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/stat_rx_control_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/stat_tx_control_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/tx_allow
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/tx_data
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/tx_fsm_state
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/tx_k
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/tx_pcs_rst
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/tx_pll_lol
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/tx_serdes_rst
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/wa_position
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/wa_position_rx
add wave -noupdate -divider Slave
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/CLEAR
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/CLK
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/CLK_EN
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/CLK_RX_FULL_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/CLK_RX_HALF_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/CTRL_DEBUG
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/CTRL_OP
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/MED_DATAREADY_IN
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/MED_DATAREADY_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/MED_DATA_IN
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/MED_DATA_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/MED_PACKET_NUM_IN
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/MED_PACKET_NUM_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/MED_READ_IN
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/MED_READ_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/RESET
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/RX_DLM
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/RX_DLM_WORD
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/STAT_DEBUG
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/STAT_OP
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/SYSCLK
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/TX_DLM
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/TX_DLM_WORD
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/clk_200_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/clk_200_internal
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/clk_rx_full
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/clk_rx_half
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/clk_tx_full
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/clk_tx_half
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/debug_reg
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/debug_rx_control_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/debug_tx_control_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/got_link_ready_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/lsm_status
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/make_link_reset_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/request_retr_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/request_retr_position_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/rst_n
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/rst_qd
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/rx_allow
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/rx_cdr_lol
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/rx_data
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/rx_error
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/rx_fsm_state
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/rx_k
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/rx_los_low
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/rx_pcs_rst
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/rx_serdes_rst
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/send_link_reset_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/serdes_rst_qd
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/start_retr_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/start_retr_position_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/start_timer
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/stat_rx_control_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/stat_tx_control_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/tx_allow
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/tx_data
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/tx_fsm_state
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/tx_k
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/tx_pcs_rst
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/tx_pll_lol
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/tx_serdes_rst
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/wa_position
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/wa_position_rx
add wave -noupdate -divider {Slave RX}
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/DEBUG_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/GOT_LINK_READY
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/MAKE_RESET_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/REQUEST_POSITION_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/REQUEST_RETRANSMIT_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/RX_DATA_IN
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/RX_DATA_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/RX_DLM_WORD
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/RX_PACKET_NUMBER_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/RX_WRITE_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/SEND_LINK_RESET_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/START_POSITION_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/START_RETRANSMIT_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/STAT_REG_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/ct_fifo_afull
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/ct_fifo_data_out
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/ct_fifo_empty
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/ct_fifo_full
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/ct_fifo_read
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/ct_fifo_reset
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/ct_fifo_write
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/got_link_ready_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/last_ct_fifo_empty
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/last_ct_fifo_read
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/make_reset_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/next_sop
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/reg_rx_data_in
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/reg_rx_k_in
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/rx_data
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/rx_dlm_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/rx_dlm_word_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/rx_state
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/rx_state_bits
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/send_link_reset_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/start_retr_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/start_retr_pos_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_CONTROL/tmp_link_ready_i
add wave -noupdate -divider {Slave RX Reset}
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/STATE_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/WA_POSITION
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/counter2
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/cs
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/ns
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/reset_timer2
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/rx_lol_los
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/rx_lol_los_del
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/rx_lol_los_int
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/rx_los_low_int
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/rx_pcs_rst_ch_c_int
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/rx_serdes_rst_ch_c_int
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/timer1
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/timer2
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_RX_FSM/tx_pll_lol_qd_s_int
add wave -noupdate -divider {Slave TX Reset}
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_TX_FSM/RST_QD_C_int
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_TX_FSM/STATE_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_TX_FSM/TIMER1
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_TX_FSM/TIMER2
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_TX_FSM/counter1
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_TX_FSM/counter2
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_TX_FSM/cs
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_TX_FSM/ns
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_TX_FSM/reset_timer1
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_TX_FSM/reset_timer2
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_TX_FSM/tx_pcs_rst_ch_c_int
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_SLAVE/THE_TX_FSM/tx_pll_lol_qd_s_int
add wave -noupdate -divider {Master RX}
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/DEBUG_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/GOT_LINK_READY
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/MAKE_RESET_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/REQUEST_POSITION_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/REQUEST_RETRANSMIT_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/RX_DATA_IN
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/RX_DATA_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/RX_DLM_WORD
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/RX_PACKET_NUMBER_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/RX_WRITE_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/SEND_LINK_RESET_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/START_POSITION_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/START_RETRANSMIT_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/STAT_REG_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/ct_fifo_afull
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/ct_fifo_data_out
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/ct_fifo_empty
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/ct_fifo_full
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/ct_fifo_read
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/ct_fifo_reset
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/ct_fifo_write
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/got_link_ready_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/last_ct_fifo_empty
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/last_ct_fifo_read
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/make_reset_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/next_sop
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/reg_rx_data_in
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/reg_rx_k_in
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/rx_data
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/rx_dlm_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/rx_dlm_word_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/rx_state
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/rx_state_bits
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/send_link_reset_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/start_retr_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/start_retr_pos_i
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_CONTROL/tmp_link_ready_i
add wave -noupdate -divider {Master TX Reset}
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_TX_FSM/RST_QD_C_int
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_TX_FSM/STATE_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_TX_FSM/TIMER1
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_TX_FSM/TIMER2
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_TX_FSM/counter1
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_TX_FSM/counter2
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_TX_FSM/cs
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_TX_FSM/ns
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_TX_FSM/reset_timer1
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_TX_FSM/reset_timer2
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_TX_FSM/tx_pcs_rst_ch_c_int
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_TX_FSM/tx_pll_lol_qd_s_int
add wave -noupdate -divider {Master RX Reset}
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/STATE_OUT
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/WA_POSITION
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/counter2
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/cs
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/ns
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/reset_timer2
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/rx_lol_los
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/rx_lol_los_del
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/rx_lol_los_int
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/rx_los_low_int
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/rx_pcs_rst_ch_c_int
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/rx_serdes_rst_ch_c_int
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/timer1
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/timer2
add wave -noupdate -radix hexadecimal /med_ecp3_sfp_sync_tb/THE_MASTER/THE_RX_FSM/tx_pll_lol_qd_s_int
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3980337070 ps} 0}
configure wave -namecolwidth 218
configure wave -valuecolwidth 40
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {3980233620 ps} {3980498420 ps}
